baseURL = "https://rainwatertornado.cloud/"
defaultContentLanguage = "en"
languageCode = "en-us"
title = "Rainwater Tornado"
theme = "m10c"

[[menu.main]]
name = "Browse"
url = "/collections/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "Submit/Help Out"
url = "/about/how-to-help/"
weight = 3

[params]
author = "Rainwater Tornado"
avatar = "logo.png"
description = "Preserving archives and collections of pony music"
favicon = "/logo.png"

[params.style]
darkestColor = "#444444" #Sidebar
darkColor = "#004444" #Main content area
lightColor = "#ffffff" #Primary text
lightestColor = "#ffffff" #Titles
primaryColor = "#00ffff" #Secondary text

[permalinks]
news = "/:section/:year/:month/:slug"
updates = "/:section/:year/:month/:slug"

[taxonomies]
tag = "tags"